# Generated by Django 5.1.2 on 2024-10-29 13:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0003_alter_post_options_post_artist_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=300, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics/')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=300, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
