# Generated by Django 5.1.2 on 2024-10-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0004_post2'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='artist',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
