# Generated by Django 5.1.2 on 2024-10-29 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0005_post2_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post2',
            old_name='image',
            new_name='images',
        ),
    ]
