# Generated by Django 5.1.2 on 2024-10-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0007_tag_post_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
